### ISSUE TITLE
please create a .Xresources verison

### ISSUE THREAD

**Issue by ghost** [AlessandroYorba/Sierra#2]
To work with urxvt. I've already converted the colors to definitions but I don't know which to assign each color (e.g. *.color0-15 or URxvt.color0-15)

```
#define Abyss       #000000
#define Lilac       #5f5f87
#define Cactus      #5f8700
#define Lake        #5f8787
#define Dusk        #875f5f
#define Heather     #8787af
#define Sage        #87af5f
#define Marsh       #87af87
#define Oasis       #87afaf
#define Azure       #87afd7
#define Agave       #87d787
#define Bluebells   #af5f00
#define Firecracker #af5f5f
#define Evening     #af8787
#define Flats       #afaf87
#define Lavender    #afafd7
#define Nolana      #afd7d7
#define Rose        #d75f5f
#define Bellflower  #d78787
#define Mallow      #dfaf5f
#define Dune        #dfdfaf
#define Stars       #dfdfdf
#define Claret      #ff8787
#define Sunset      #ffafaf
#define Salt        #ffffff
#define Pitch       #080808
#define Midnight    #121212
#define Twilight    #1c1c1c
#define Shadow      #262626
#define Day         #303030
#define Shade       #3a3a3a
#define Pebble      #4e4e4e
#define Graphite    #585858
#define Slate       #767676
#define Stone       #8a8a8a
#define Cloud       #e4e4e4
```

**Comment by AlessandroYorba** [comment]
See if this does the trick, and if it works I'll post this and the other versions for each of the other modes. The following should be the day version:

```
! special
*.foreground:   #e4e4e4
*.background:   #303030
*.cursorColor:  #e4e4e4

! black
*.color0:       #4d4d4d
*.color8:       #555555

! red
*.color1:       #af5f5f
*.color9:       #af5f5f

! green
*.color2:       #d75f5f
*.color10:      #d75f5f

! yellow
*.color3:       #afd7d7
*.color11:      #b0d6d7

! blue
*.color4:       #af8787
*.color12:      #af8787

! magenta
*.color5:       #dfaf5f
*.color13:      #dfaf5f

! cyan
*.color6:       #ffa0a0
*.color14:      #fda0a0

! white
*.color7:       #f5deb3
*.color15:      #ffffff
```

**Comment by ghost** [comment]
works nicely so far, thanks so much!

**Comment by AlessandroYorba** [comment]
I'll get to work on the other values. Thanks for the feedback

**Comment by ghost** [comment]
Encountered one problem so far:
![1457812434](https://cloud.githubusercontent.com/assets/2244606/13724923/43a2ed36-e849-11e5-84c7-a59942ee115f.png)
When I use 'ls' the highlighted text is very difficult to read. Other than that it's been working great.

**Comment by AlessandroYorba** [comment]
@bigmittens 
Mmmm. I think you're on to something. 
Here's what it looks like on my end:

iTerm2 
![itermsierra](https://cloud.githubusercontent.com/assets/11221489/13727933/2f3aa45c-e8bb-11e5-8c77-4f34243c524c.png)

Let's see if we can darken the foreground text for those directories. Open your config and change the perviously listed .color0 to:

```
! black
*.color0:       #333333
```

Let me know if that does the trick!

**Comment by ghost** [comment]
Seems to look the same. Are you sure color0 is the foreground color there? The highlighted documents are "drwxrwxrwx", maybe that has a different foreground?

**Comment by AlessandroYorba** [comment]
@bigmittens I'm not sure. Perhaps the terminal color settings toggle from .color0 to .color8 depending on permissions. As far as I can tell, the only other color in the bunch that's light grey is .color8 #555555. Can you see if this change makes a difference. 

```
*.color8:       #333333
```

**Comment by ghost** [comment]
Still looks the same. Really strange.

**Comment by benjumanji** [comment]
Any chance of seeing the others ported .Xresources? Would love to see the twilight one!

**Comment by AlessandroYorba** [comment]
@benjumanji try the following for the Twilight version. As soon as I can figure out the solution for issue that @bigmittens pointed out, I'll make sure to post the other colors.

```
! special
*.foreground:   #e4e4e4
*.background:   #1c1c1c
*.cursorColor:  #e4e4e4

! black
*.color0:       #4d4d4d
*.color8:       #555555

! red
*.color1:       #af5f5f
*.color9:       #af5f5f

! green
*.color2:       #d75f5f
*.color10:      #d75f5f

! yellow
*.color3:       #afd7d7
*.color11:      #b0d6d7

! blue
*.color4:       #af8787
*.color12:      #af8787

! magenta
*.color5:       #dfaf5f
*.color13:      #dfaf5f

! cyan
*.color6:       #ffa0a0
*.color14:      #fda0a0

! white
*.color7:       #f5deb3
*.color15:      #ffffff

```

**Comment by benjumanji** [comment]
Yaassss!

Thanks, thanks, thanks. I'll try this out when I get home.

**Comment by benjumanji** [comment]
I have been using this for a week or so, seems to work flawlessly.

**Comment by AlessandroYorba** [comment]
Thank you @benjumanji for feedback! I'll add the remaining modes soon

**Comment by AlessandroYorba** [comment]
@bigmittens @benjumanji 
Heads up. I will be changing a color0 for each of the sierra .Xresources when they are released. The issue that bigmittens was having appeared, just appeared in my environment when using Tmux. I'm hoping that if I darken color0 for each mode that it might help for that readability issue. keep you guys posted, but in the mean time I recommend that you change color0 to the same hex# value as the background color.

**Comment by benjumanji** [comment]
Thanks for the heads up.
