### ISSUE TITLE
Background changes while scrolling terminal window

### ISSUE THREAD

**Issue by aaaleshaaa** [AlessandroYorba/Sierra#3]
I appreciate the theme but experience a problem with background while scrolling.
See attachment.
![vim_in_terminal_sierra](https://cloud.githubusercontent.com/assets/2562465/15538067/861cb908-2282-11e6-9c46-8bea5d5edc2f.png)

**Comment by AlessandroYorba** [comment]
@cahes Hi, could you give me more info on your environment? I can't reproduce that behavior here. I'm using iTerm 2.1.4, tmux 2.1, and colorscheme sierra

**Comment by aaaleshaaa** [comment]
Hi,
I'm using GNOME Terminal 3.20.2 @ Arch Linux (kernel 4.5.4-1-ARCH)
The issues is observing when scrolling with mouse wheel, everything is OK with PageDown.
The background of a scrolled zone becomes black what contrasts to theme background which is lighter.

**Comment by AlessandroYorba** [comment]
Very odd indeed. Here are a few others that have had a similar issue when using Vim in GNOME. 
[Fixing Vim's Background Color Erase for 256-color tmux and GNU screen](http://sunaku.github.io/vim-256color-bce.html)
[In vim, background color changes on scrolling](http://superuser.com/questions/457911/in-vim-background-color-changes-on-scrolling)

Their solution, was to add this the .vimrc

``` VimL
if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  set t_ut=
endif
```

Please keep me posted, if it works I will make sure to either add the snippet to the actual color scheme or update the markdown on the page

**Comment by aaaleshaaa** [comment]
Alessandro,

I added that instructions to the .vimrc and now everything works fine.

Much thanks for the help,
Alexey Voytekhovskiy

**Comment by AlessandroYorba** [comment]
Thank you for bringing it to my attention. Oh by the way, in Vim 8 there will be support for gui colors in the terminal if the terminal that's running Vim also supports 24bit colors. So the if statement you added to your .vimrc might need updating or adjusting when you want to start using gui colors in the terminal. Luckily both Sierra and Alduin gui use term colors. thanks again

**Comment by aaaleshaaa** [comment]
Oh, very interesting. I'll inform you if there will be some issues with that. My Arch Linux has rolling-release model, thus, I got the 8th version rather soon.
